/*
 * Guessing Game - player tries to guess random number generated by computer
 * Author: Emily MacPherson
 * Date: 9/16/20
 */

import java.util.Scanner;

public class GuessingGame 
{
	//Main Method, starts program
	public static void main(String[] args) 
	{
		new GuessingGame();
	}
	
	//Constructor for GuessingGame
	public GuessingGame()
	{
		boolean stillPlaying = true;
		
		while(stillPlaying == true)
		{
			int randNum = (int)(Math.random() * 51);
			System.out.println("I've chosen a random number between 1 and 50, make a guess.");
			Scanner scanner = new Scanner(System.in);
			int guess = -69;
			int guessesMade = 0;
			
			while(guess != randNum)
			{
				String input = scanner.nextLine();
				guess = Integer.parseInt(input);
				guessesMade += 1;
				if(guess < randNum)
				{
					System.out.println("Too low, try again.");
				}
				if(guess > randNum)
				{
					System.out.println("Too high, try again");
				}
				if(guess < 0 || guess > 50)
				{
					System.out.println("Also that's not in the range you buffoon :D");
				}
			}
			
			System.out.println("Congo rats, you guessed it!");
			System.out.println("It took you " + guessesMade + " guesses.");
			if(guessesMade < 5)
			{
				System.out.println("That was fast :D");
			}
			boolean hasAnswered = false;
			while(hasAnswered == false)
			{
				System.out.println("Play again?");
				String yesno = scanner.nextLine();
				if(yesno.equals("yes") || yesno.equals("ye") || yesno.equals("yee") || yesno.equals("yeet") || yesno.equals("y"))
				{
					hasAnswered = true;
					stillPlaying = true;
				}
				else if(yesno.equals("no") || yesno.equals("nope") || yesno.equals("nah") || yesno.equals("n"))
				{
					hasAnswered = true;
					System.out.println("Adiós");
					stillPlaying = false;
				}
				else
				{
					System.out.println("That's not an answer :/");
				}
			}
			
		}
	}
	
	
}
